# Generated by Django 6.0.5 on 2026-06-07 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_teammember_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='team.team'),
        ),
    ]
